package server

import (
	"net/http"

	"github.com/gin-contrib/cors"
	"github.com/gin-gonic/gin"
	"github.com/olebedev/staticbin"
	"github.com/plan97/gofileserver/config"
	"github.com/plan97/gofileserver/handlers"
)

//go:generate go-bindata -pkg server -prefix dist/go-file-server dist/...

// Serve using the provided configuration.
func Serve(c *config.Config) (err error) {
	router := gin.Default()
	if c.AllowCors {
		router.Use(cors.Default())
	}

	static := router.Group("/static")
	static.Static("", c.Dir)

	api := router.Group("/api")
	api.POST("list_dir_files", handlers.ListDirFiles(c.Dir))

	// Serves the "static" directory's files from binary data.
	// You have to pass the "Asset" function generated by
	// go-bindata (https://github.com/jteeuwen/go-bindata).
	router.Use(staticbin.Static(Asset, staticbin.Options{
		// Dir prefix will be trimmed. It needs to separate namespace.
		Dir:         "",
		IndexFile:   "index.html",
		SkipLogging: true,
	}))

	router.NoRoute(func(c *gin.Context) {
		c.Redirect(http.StatusTemporaryRedirect, "/")
	})

	if c.HTTPS {
		err = router.RunTLS(c.Addr, c.SSLCertFile, c.SSLKeyFile)
	} else {
		err = router.Run(c.Addr)
	}
	return
}
