name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.2

      - name: Add missing and remove unused modules
        run: go mod tidy

      - name: Install
        run: go install ./...

      - name: Test
        run: go test -v ./...
